server:
  port: 8080

aws:
  s3:
    photos:
      bucket: edx-images-bucket
      prefix: photos/
  recognition:
    maximum_labels: 10
    minimum_confidence: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://edx-captureme-local.cdtopxajsx6m.us-west-2.rds.amazonaws.com/captureme
    username: web_user
    password: password